android.useAndroidX=true
kotlin.code.style=official
# Force TLS 1.2 for Gradle JVM to avoid SSL handshake failures on some Java runtimes / networks
# This helps when the server (dl.google.com / repo.maven.apache.org) requires TLSv1.2
org.gradle.jvmargs=-Dhttps.protocols=TLSv1.2 -Djava.net.preferIPv4Stack=true -Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=10809 -Dhttps.proxyHost=127.0.0.1 -Dhttps.proxyPort=10809 -Xmx1536m
